[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  included_files = ["main.py"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
